apiVersion : apps/v1
kind: Deployment
metadata:
  name: ecommerce 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce 
    spec:
      containers:
        - name: ecommerce 
          image: ecommercedev00.azurecr.io/ecommerce
          ports:
          - containerPort: 80