// Code generated by MockGen. DO NOT EDIT.
// Source: payments.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	model "dev.azure.com/jjoogam/Ecommerce-core/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPaymentQueryRepository is a mock of PaymentQueryRepository interface.
type MockPaymentQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentQueryRepositoryMockRecorder
}

// MockPaymentQueryRepositoryMockRecorder is the mock recorder for MockPaymentQueryRepository.
type MockPaymentQueryRepositoryMockRecorder struct {
	mock *MockPaymentQueryRepository
}

// NewMockPaymentQueryRepository creates a new mock instance.
func NewMockPaymentQueryRepository(ctrl *gomock.Controller) *MockPaymentQueryRepository {
	mock := &MockPaymentQueryRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentQueryRepository) EXPECT() *MockPaymentQueryRepositoryMockRecorder {
	return m.recorder
}

// DeletePayment mocks base method.
func (m *MockPaymentQueryRepository) DeletePayment(ctx context.Context, customerNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePayment", ctx, customerNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePayment indicates an expected call of DeletePayment.
func (mr *MockPaymentQueryRepositoryMockRecorder) DeletePayment(ctx, customerNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePayment", reflect.TypeOf((*MockPaymentQueryRepository)(nil).DeletePayment), ctx, customerNumber)
}

// FindPayment mocks base method.
func (m *MockPaymentQueryRepository) FindPayment(ctx context.Context, customerNumber int) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPayment", ctx, customerNumber)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPayment indicates an expected call of FindPayment.
func (mr *MockPaymentQueryRepositoryMockRecorder) FindPayment(ctx, customerNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPayment", reflect.TypeOf((*MockPaymentQueryRepository)(nil).FindPayment), ctx, customerNumber)
}

// GetPayments mocks base method.
func (m *MockPaymentQueryRepository) GetPayments(ctx context.Context) ([]model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayments", ctx)
	ret0, _ := ret[0].([]model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayments indicates an expected call of GetPayments.
func (mr *MockPaymentQueryRepositoryMockRecorder) GetPayments(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayments", reflect.TypeOf((*MockPaymentQueryRepository)(nil).GetPayments), ctx)
}
